import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube, 
  AiOutlineDownload, AiFillMobile, AiFillMail,AiOutlineWhatsApp, AiFillGithub, AiOutlineMail } from 'react-icons/ai';
import Image from 'next/image';
import avatar from '../public/Arnold.jpg'
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import figma from '../public/figma.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title> Arnold Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white" >
        <section className="min-h-screen">
          <nav className="p-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons pr-10 pl-0" >Arnold</h1>
            <ul className="flex items-center ">
              <li className=""><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/></li>
              
              <li><a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="./public/Arnold.pdf" download=''> Resume </a> </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Arnold Ramodike</h2>
            <h3 className="text-2xl pt-2 md:text-3xl"> Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white"> 
              I am a Developer who has a knack for numbers and love big data.
              Analyzing data and developing insights and
              reports that help the management take business decisions.
              I collaborate well with the technical and business represantatives in the design, 
              and development of applications and reports.
              </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white ">
            <AiFillLinkedin className='cursor-pointer'/>
            <AiFillMail className='cursor-pointer' href="https://github.com/ArnoldRamodike"/>
            <AiFillGithub/>
            <AiOutlineWhatsApp/>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 ">
          <Image src={avatar} layout="fill" objectFit="cover" alt=""/>
          </div>
        </section> 
        <section> 
          <div>
            <h3 className="text-3xl py-1 pt-10 text-center">Work Experience</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">I have worked with some of the most amazing
            <span className="text-teal-500"> agencies </span>
            consulted for <span className="text-teal-500">stargazing </span> 
              and collaborated with talented people to create digital functionalities for both business and consumer use
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white"> </p>
          </div>
          <div className="lg:flex gap-20 ">
          
            <div className="text-center  rounded-xl my-10">
              <Image src={design} width={100} height={100} alt="" className="mx-auto"/>       
              <h3 className="text-lg font-medium pt-8 pb-2 ">Previous Companies</h3>
              <p className="text-md py-2 leading-8 text-gray-800"></p>
              <h4></h4>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-white">
              <p className="text-teal-500 py-1">Unitec Solution<span className="text-black pl-5 dark:text-white">2020-2021</span></p>
              <h4 className="text-gray-800 py-2 dark:text-white">Trainee</h4>
              <p className="text-gray-800 py-2 dark:text-white">Web Development using Laravel/PHP and HTML/CSS and Java Script</p>
              </div>
              
              <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-white">
              <p className="text-teal-500 py-1">Singular Systems <span className="text-black pl-5 dark:text-white">2021-2023</span></p>
              <h4 className="text-gray-800 py-2 dark:text-white">Junior Programmer</h4>
              <p className="text-gray-800 py-2 dark:text-white">Developing new functions into test Automation Framework in .NET and React.
              Microsoft Dynamics 365 Customizations in C# and Java Script. Production support for international clients.</p>
              </div>
            </div>
          </div>
        </section>

        <section className='flex-auto'>
          <div>
            <h3 className="text-3xl py-1 text-center">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white md:text-xl max-w-lg mx-auto"> Below are some of the 
            <span className="text-teal-500"> skillsets </span>
           That i <span className="text-teal-500">posses </span> for both business and consumer use
            </p>
          </div>
          <div className="lg:flex gap-20 flex-row">
            <div className="text-center shadow-lg p-10  rounded-xl my-10 dark:shadow-white">
              <Image src={figma} width={100} height={100} alt="" className="mx-auto"/>             
              <h3 className="text-lg font-medium pt-8 pb-2">Frontend</h3>
              <p className="text-gray-800 dark:text-white py-1">HTML5/CSS3</p>
              <p className="text-gray-800 dark:text-white py-1">Javascript</p>
              <p className="text-gray-800 dark:text-white py-1">Typescript</p>
              <p className="text-gray-800 dark:text-white py-1">.NET</p>
              <p className="text-gray-800 dark:text-white py-1">Saas</p>
              <p className="text-gray-800 dark:text-white py-1">Tailwindcss</p>
              <p className="text-gray-800 dark:text-white py-1">React JS</p>
              <p className="text-gray-800 dark:text-white py-1">Next JS</p>
              <p className="text-gray-800 dark:text-white py-1">Vue JS</p>
              <p className="text-gray-800 dark:text-white py-1">Angular JS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-white">
              <Image src={code} width={100} height={100} alt="" className="mx-auto"/>             
              <h3 className="text-lg font-medium pt-8 pb-2">Backend </h3>
              <p className="text-gray-800 dark:text-white py-1">C# & C++</p>
              <p className="text-gray-800 dark:text-white py-1">Laravel</p>
              <p className="text-gray-800 dark:text-white py-1">Node Js</p>
              <p className="text-gray-800 dark:text-white py-1">Express Js</p>
              <p className="text-gray-800 dark:text-white py-1">Java</p>
              <p className="text-gray-800 dark:text-white py-1">Python</p>
              <p className="text-gray-800 dark:text-white py-1">php</p>
              <p className="text-gray-800 dark:text-white py-1">Source Control</p>
              <p className="text-gray-800 dark:text-white py-1">Shell</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-white">
              <Image src={consulting} width={100} height={100} alt="" className="mx-auto"/>             
              <h3 className="text-lg font-medium pt-8 pb-2">Database</h3>
              <p className="text-gray-800 dark:text-white py-1">SQL & MySQL</p>
              <p className="text-gray-800 dark:text-white py-1">Mongo Db</p>

            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 text-center">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white"> These are some of the  
            <span className="text-teal-500"> Projects </span>
            That i have worked on. The code for all these projects is in my <span className="text-teal-500">Github </span> 
             repositories.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500">E-Commerce App</h3>
              <a href="https://riccoadmin.netlify.app">
              <Image src={web1} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500"> Full-Stack Blog Application </h3>
              <a href="https://riccoadmin.netlify.app">
              <Image src={web2} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500">Music App with shazam API</h3>
              <a href="https://riccolyriks.netlify.app">
              <Image src={web3} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500">The Admin Dashboard </h3>
              <a href="https://riccoadmin.netlify.app">
              <Image src={web5} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500">Social Media Platform</h3>
              <a href="https://riccoadmin.netlify.app">
              <Image src={web4} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500">Front-End Design</h3>
              <a href="https://arnold-frontend.netlify.app/">
              <Image src={web6} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
          </div>
        </section>
        <section> 
          <div>
            <h3 className="text-3xl py-1 pt-10 text-center">Contacts</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white"> </p>
          </div>
          <div className="lg:flex gap-20 shadow-lg rounded-xl my-10 dark:shadow-white ">
          
            <div className="text-center  rounded-xl my-10  ">
              <Image src={design} width={100} height={100} alt="" className="mx-auto"/>       
              <h3 className="text-lg font-medium pt-8 pb-2 ">Contacts</h3>
              <p className="text-md py-2 leading-8 text-gray-800">
              How to <span className="text-teal-500"> get hold </span> of me.
              </p>
              <h4></h4>
              {/* <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <p className="text-teal-500 py-1">Phone<span className="text-black pl-5 dark:text-white">+27739710445</span></p>
              <p className="text-teal-500 py-1">Email <span className="text-black pl-5 dark:text-white">riccoarnold23@gmail.com</span></p>
              <p className="text-teal-500 py-1">Other<span className="text-black pl-5 dark:text-white">2020-2021</span></p>
              </div> */}
               <div className="text-5xl flex justify-center gap-16 py-3  text-gray-600 dark:text-white cursor-pointer">
            <AiFillLinkedin/>
            <AiFillMail href="https://github.com/ArnoldRamodike"/>
            <AiFillGithub/>
             <a href="https://riccoadmin.netlify.app" target=''> <AiOutlineWhatsApp /></a>
           </div>
            </div>
          </div>
        </section>
        <footer>
          <p className="text-gray-800 text-center text-lg shadow-lg dark:text-white"> Designed by <span className="text-teal-500">Arnold Ramodike</span> with ❤️ </p>
        </footer>
      </main>
      </div>
  );
}
